import * as fs from 'fs';
import * as path from 'path';
import type { ConfigPlugin } from 'expo/config-plugins';
import { withDangerousMod, withInfoPlist, withXcodeProject } from 'expo/config-plugins';

/**
 * Config plugin for the custom Live Photo exporter module.
 *
 * 1. Ensures the two photo-library Info.plist keys are set so that
 *    `PHPhotoLibrary.requestAuthorization(for: .addOnly)` can present a prompt
 *    without the app being terminated for a missing usage description.
 *
 * 2. Sets SWIFT_STRICT_CONCURRENCY = minimal for all build configurations.
 *    Xcode 16 bumped the default to "complete" which turns the Swift 5.10
 *    concurrency warnings into errors. Our module (and several RN pods) use
 *    patterns that are safe at runtime but not yet annotated for full strict
 *    concurrency. "minimal" restores the Xcode 15 behaviour so they compile.
 *
 * Values are only inserted when missing — existing translations are kept.
 */
const withExpoLivePhotoExporter: ConfigPlugin<void> = (config) => {
  // Step 1 — Info.plist usage descriptions
  config = withInfoPlist(config, (cfg) => {
    const plist = cfg.modResults;

    if (!plist.NSPhotoLibraryAddUsageDescription) {
      plist.NSPhotoLibraryAddUsageDescription =
        '作成した Live Photo を写真ライブラリに保存するために使用します。';
    }
    if (!plist.NSPhotoLibraryUsageDescription) {
      plist.NSPhotoLibraryUsageDescription =
        '動画を読み込み、Live Photo を作成・保存するために写真ライブラリへアクセスします。';
    }

    return cfg;
  });

  // Step 2 — SWIFT_STRICT_CONCURRENCY = minimal for the main app target (via xcodeproj)
  config = withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const buildConfigs = project.pbxXCBuildConfigurationSection();

    for (const key of Object.keys(buildConfigs)) {
      const bc = buildConfigs[key];
      if (bc && typeof bc === 'object' && bc.buildSettings) {
        bc.buildSettings.SWIFT_STRICT_CONCURRENCY = 'minimal';
      }
    }

    return cfg;
  });

  // Step 3 — SWIFT_STRICT_CONCURRENCY = minimal for ALL pod targets via Podfile post_install.
  // withXcodeProject only touches the app's .xcodeproj; pods live in Pods/Pods.xcodeproj
  // which is regenerated by `pod install` and is not available at config-plugin time.
  // CocoaPods only supports ONE post_install block, so we insert INSIDE the existing block
  // that the Expo/React Native Podfile template already provides.
  config = withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfilePath = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      let podfile = fs.readFileSync(podfilePath, 'utf-8');

      // Guard: don't insert twice. Use a unique marker rather than checking
      // for 'SWIFT_STRICT_CONCURRENCY' which may already appear inside the
      // react_native_post_install helper (setting it to 'complete').
      const MARKER = '# expo-live-photo-exporter: swift-concurrency-minimal';
      if (podfile.includes(MARKER)) {
        return cfg;
      }

      // Inject AFTER the react_native_post_install(...) call so our 'minimal'
      // value is set last and wins over anything react_native_post_install sets.
      // The RN Podfile template always contains a react_native_post_install call
      // that may span multiple lines; we look for a line that closes with `)`.
      const injection = [
        `  ${MARKER}`,
        '  # Patch openiap to fix Swift concurrency: re-capture self in Task closure list',
        '  openiap_path = File.join(File.dirname(__FILE__), "Pods", "openiap", "Sources", "OpenIapStore.swift")',
        '  if File.exist?(openiap_path)',
        '    src = File.read(openiap_path)',
        '    old_pattern = "Task { @MainActor in"',
        '    new_pattern = "Task { @MainActor [weak self] in"',
        '    patched = src.gsub(old_pattern, new_pattern)',
        '    if patched != src',
        '      File.write(openiap_path, patched)',
        '      puts "[expo-live-photo-exporter] Patched openiap OpenIapStore.swift"',
        '    end',
        '  end',
        '  installer.pods_project.targets.each do |target|',
        '    target.build_configurations.each do |bc|',
        "      bc.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'minimal'",
        "      # Ensure iOS deployment target is at least 15.1 (required by openiap >= 1.0)",
        "      current = bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET']",
        "      if current && current.to_f < 15.1",
        "        bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'",
        "      end",
        '    end',
        '  end',
      ].join('\n');

      // Try to insert right after the line that closes the react_native_post_install call.
      // That line typically looks like: `    :mac_catalyst_enabled => false\n  )\n`
      // We match the `)` that closes the call — it's the first standalone `)` after
      // the `react_native_post_install` keyword.
      const rnPostInstallCallEnd = /react_native_post_install\b[\s\S]*?\n(\s*\))/;
      const rnMatch = rnPostInstallCallEnd.exec(podfile);
      if (rnMatch) {
        const insertPos = rnMatch.index + rnMatch[0].length;
        podfile = podfile.slice(0, insertPos) + '\n' + injection + podfile.slice(insertPos);
      } else {
        // Fallback: insert right after the post_install opening line
        const anchor = 'post_install do |installer|';
        if (podfile.includes(anchor)) {
          podfile = podfile.replace(anchor, anchor + '\n' + injection);
        } else {
          podfile += '\npost_install do |installer|\n' + injection + '\nend\n';
        }
      }

      fs.writeFileSync(podfilePath, podfile);
      return cfg;
    },
  ]);

  return config;
};

export default withExpoLivePhotoExporter;
